source("paths.R")
library(tidyverse)

# -----------------------------------------------------------------------------
# These are the ID's represented in the data streams generated by MD2K
# -----------------------------------------------------------------------------

all_dir_names <- list.dirs(path = path_raw_data)
participant_dir_names <- all_dir_names[grep(pattern = "mars", x = all_dir_names, fixed = TRUE)]

list_ids <- list()

for(i in 1:length(participant_dir_names)){
  # The call to regexpr() identifies the position of "m" the first time 
  # the string "mars" appears in the directory name.
  # The directory name we will scan for "m" is specified in the argument
  # text in the call to regexpr()
  begin_position <- regexpr(pattern = "mars", text = participant_dir_names[i], fixed = TRUE)
  study_id <- substring(text =  participant_dir_names[i], first = begin_position)
  
  # At this point, most of the study_id values will have the form "mars_XX".
  # However, there will be a few which will have the form "mars_XX/some_sub_directory".
  # We need to remove "/some_sub_directory" because we are only interested in.
  trim_here <- regexpr(pattern = "/", text = study_id, fixed = TRUE)
  
  # Note that trim_here will have the value -1 if "/some_sub_directory" does not exist.
  # Therefore, substr() should only be called when "/some_sub_directory" exists.
  if(trim_here != -1){
    study_id <- substr(x = study_id, start = 1, stop = trim_here-1)
  }
  
  list_ids <- append(list_ids, list(study_id))
}

arr_ids <- unlist(list_ids)
arr_ids <- unique(arr_ids)

# -----------------------------------------------------------------------------
# Remove ID's which were "trashed" by study staff
# -----------------------------------------------------------------------------

# The grafana ID "mars_63" was "trashed" by study staff and replaced by "mars_70"
trashed_ids <- c("mars_63") 
arr_ids <- arr_ids[!(arr_ids %in% trashed_ids)]

# -----------------------------------------------------------------------------
# Save ID's
# -----------------------------------------------------------------------------

list_ids <- as.list(arr_ids)

saveRDS(list_ids, file.path(path_manipulated_data, "list_ids.rds"))

