---
title: "Explore Imputation Model Predictors: Primary proximal outcome among participant-decision points in stratum 1"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output: 
  html_document:
    toc: TRUE
    toc_depth: 4
    number_sections: TRUE
---

```{=html}
<style type="text/css">
.main-container {
  max-width: 3800px !important;
  margin-left: auto;
  margin-right: auto;
}
</style>
```

```{r global_options, include=FALSE}
knitr::opts_chunk$set(tidy = TRUE)
knitr::opts_chunk$set(fig.pos = 'H')
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = FALSE)
options(width = 10000)
```

```{r}
source("paths.R")
library(knitr)
library(tidyverse)
library(geepack)

type_one_error_rate <- 0.05
```

```{r}
dat_primary_aim <- readRDS(file = file.path(path_manipulated_data, "dat_primary_aim.rds"))

dat_matched_conditions <- readRDS(file = file.path(path_manipulated_data, "dat_matched_conditions.rds"))
dat_matched_conditions <- dat_matched_conditions %>% 
  select(mars_id, decision_point, 
         privacy_data_not_found_quick_survey, driving_data_not_found_quick_survey, 
         privacy_data_not_found_rand, driving_data_not_found_rand,
         privacy_data_not_found_ema, driving_data_not_found_ema) %>%
  mutate(driving_data_not_found_combined = if_else((driving_data_not_found_quick_survey == 0) & (driving_data_not_found_rand == 0), 1, 0))
dat_primary_aim <- left_join(x = dat_primary_aim, y = dat_matched_conditions, by = join_by(mars_id == mars_id, decision_point == decision_point))

dat_primary_aim <- dat_primary_aim %>% 
  mutate(is_complete_v1_quest = if_else(v1_baseline_quest_complete == "Complete", 1, 0))
```

```{r}
dat_included <- dat_primary_aim %>% filter(eligibility == 1) %>% filter(any_recent_eligible_dp == 0)
```

```{r}
list_dat_out <- list()
list_dat_out_quadratic <- list()
```

# Enter predictors as a linear main effect


```{r}
rhs <- "any_response_2qs"
lhs <- "Y"
my_formula <- formula(paste(lhs, "~", rhs, sep = ""))

dat_for_analysis <- dat_included %>% select(all_of(c("participant_id", "decision_point", lhs, rhs)))
rows_no_miss <- dat_for_analysis %>% complete.cases(.)
dat_for_analysis_cc <- dat_for_analysis %>% filter(rows_no_miss)

fit <- geeglm(my_formula, 
              data = dat_for_analysis_cc, 
              id = participant_id,
              waves = decision_point,
              family = binomial)
dat_fit_summary <- summary(fit)[["coefficients"]]

conf_int_lb <- dat_fit_summary[["Estimate"]] - qnorm(1 - type_one_error_rate/2) * dat_fit_summary[["Std.err"]]
conf_int_ub <- dat_fit_summary[["Estimate"]] + qnorm(1 - type_one_error_rate/2) * dat_fit_summary[["Std.err"]]

dat_out <- data.frame(predictor = rhs,
                      est_beta0 = dat_fit_summary[["Estimate"]][1],
                      conf_int_lb_beta0 = conf_int_lb[1],
                      conf_int_ub_beta0 = conf_int_ub[1],
                      est_beta1 = dat_fit_summary[["Estimate"]][2],
                      conf_int_lb_beta1 = conf_int_lb[2],
                      conf_int_ub_beta1 = conf_int_ub[2])

list_dat_out <- append(list_dat_out, list(dat_out))
```

```{r}
rhs <- "driving_data_not_found_combined"
lhs <- "Y"
my_formula <- formula(paste(lhs, "~", rhs, sep = ""))

dat_for_analysis <- dat_included %>% select(all_of(c("participant_id", "decision_point", lhs, rhs)))
rows_no_miss <- dat_for_analysis %>% complete.cases(.)
dat_for_analysis_cc <- dat_for_analysis %>% filter(rows_no_miss)

fit <- geeglm(my_formula, 
              data = dat_for_analysis_cc, 
              id = participant_id,
              waves = decision_point,
              family = binomial)
dat_fit_summary <- summary(fit)[["coefficients"]]

conf_int_lb <- dat_fit_summary[["Estimate"]] - qnorm(1 - type_one_error_rate/2) * dat_fit_summary[["Std.err"]]
conf_int_ub <- dat_fit_summary[["Estimate"]] + qnorm(1 - type_one_error_rate/2) * dat_fit_summary[["Std.err"]]

dat_out <- data.frame(predictor = rhs,
                      est_beta0 = dat_fit_summary[["Estimate"]][1],
                      conf_int_lb_beta0 = conf_int_lb[1],
                      conf_int_ub_beta0 = conf_int_ub[1],
                      est_beta1 = dat_fit_summary[["Estimate"]][2],
                      conf_int_lb_beta1 = conf_int_lb[2],
                      conf_int_ub_beta1 = conf_int_ub[2])

list_dat_out <- append(list_dat_out, list(dat_out))
```

```{r}
rhs <- "hour_coinflip_local"
lhs <- "Y"
my_formula <- formula(paste(lhs, "~", rhs, sep = ""))

dat_for_analysis <- dat_included %>% select(all_of(c("participant_id", "decision_point", lhs, rhs)))
rows_no_miss <- dat_for_analysis %>% complete.cases(.)
dat_for_analysis_cc <- dat_for_analysis %>% filter(rows_no_miss)

fit <- geeglm(my_formula, 
              data = dat_for_analysis_cc, 
              id = participant_id,
              waves = decision_point,
              family = binomial)
dat_fit_summary <- summary(fit)[["coefficients"]]

conf_int_lb <- dat_fit_summary[["Estimate"]] - qnorm(1 - type_one_error_rate/2) * dat_fit_summary[["Std.err"]]
conf_int_ub <- dat_fit_summary[["Estimate"]] + qnorm(1 - type_one_error_rate/2) * dat_fit_summary[["Std.err"]]

dat_out <- data.frame(predictor = rhs,
                      est_beta0 = dat_fit_summary[["Estimate"]][1],
                      conf_int_lb_beta0 = conf_int_lb[1],
                      conf_int_ub_beta0 = conf_int_ub[1],
                      est_beta1 = dat_fit_summary[["Estimate"]][2],
                      conf_int_lb_beta1 = conf_int_lb[2],
                      conf_int_ub_beta1 = conf_int_ub[2])

list_dat_out <- append(list_dat_out, list(dat_out))
```

```{r}
rhs <- "is_complete_v1_quest"
lhs <- "Y"
my_formula <- formula(paste(lhs, "~", rhs, sep = ""))

dat_for_analysis <- dat_included %>% select(all_of(c("participant_id", "decision_point", lhs, rhs)))
rows_no_miss <- dat_for_analysis %>% complete.cases(.)
dat_for_analysis_cc <- dat_for_analysis %>% filter(rows_no_miss)

fit <- geeglm(my_formula, 
              data = dat_for_analysis_cc, 
              id = participant_id,
              waves = decision_point,
              family = binomial)
dat_fit_summary <- summary(fit)[["coefficients"]]

conf_int_lb <- dat_fit_summary[["Estimate"]] - qnorm(1 - type_one_error_rate/2) * dat_fit_summary[["Std.err"]]
conf_int_ub <- dat_fit_summary[["Estimate"]] + qnorm(1 - type_one_error_rate/2) * dat_fit_summary[["Std.err"]]

dat_out <- data.frame(predictor = rhs,
                      est_beta0 = dat_fit_summary[["Estimate"]][1],
                      conf_int_lb_beta0 = conf_int_lb[1],
                      conf_int_ub_beta0 = conf_int_ub[1],
                      est_beta1 = dat_fit_summary[["Estimate"]][2],
                      conf_int_lb_beta1 = conf_int_lb[2],
                      conf_int_ub_beta1 = conf_int_ub[2])

list_dat_out <- append(list_dat_out, list(dat_out))
```

```{r}
rhs <- "age"
lhs <- "Y"
my_formula <- formula(paste(lhs, "~", rhs, sep = ""))

dat_for_analysis <- dat_included %>% select(all_of(c("participant_id", "decision_point", lhs, rhs)))
rows_no_miss <- dat_for_analysis %>% complete.cases(.)
dat_for_analysis_cc <- dat_for_analysis %>% filter(rows_no_miss)

fit <- geeglm(my_formula, 
              data = dat_for_analysis_cc, 
              id = participant_id,
              waves = decision_point,
              family = binomial)
dat_fit_summary <- summary(fit)[["coefficients"]]

conf_int_lb <- dat_fit_summary[["Estimate"]] - qnorm(1 - type_one_error_rate/2) * dat_fit_summary[["Std.err"]]
conf_int_ub <- dat_fit_summary[["Estimate"]] + qnorm(1 - type_one_error_rate/2) * dat_fit_summary[["Std.err"]]

dat_out <- data.frame(predictor = rhs,
                      est_beta0 = dat_fit_summary[["Estimate"]][1],
                      conf_int_lb_beta0 = conf_int_lb[1],
                      conf_int_ub_beta0 = conf_int_ub[1],
                      est_beta1 = dat_fit_summary[["Estimate"]][2],
                      conf_int_lb_beta1 = conf_int_lb[2],
                      conf_int_ub_beta1 = conf_int_ub[2])

list_dat_out <- append(list_dat_out, list(dat_out))
```

```{r}
rhs <- "is_male"
lhs <- "Y"
my_formula <- formula(paste(lhs, "~", rhs, sep = ""))

dat_for_analysis <- dat_included %>% select(all_of(c("participant_id", "decision_point", lhs, rhs)))
rows_no_miss <- dat_for_analysis %>% complete.cases(.)
dat_for_analysis_cc <- dat_for_analysis %>% filter(rows_no_miss)

fit <- geeglm(my_formula, 
              data = dat_for_analysis_cc, 
              id = participant_id,
              waves = decision_point,
              family = binomial)
dat_fit_summary <- summary(fit)[["coefficients"]]

conf_int_lb <- dat_fit_summary[["Estimate"]] - qnorm(1 - type_one_error_rate/2) * dat_fit_summary[["Std.err"]]
conf_int_ub <- dat_fit_summary[["Estimate"]] + qnorm(1 - type_one_error_rate/2) * dat_fit_summary[["Std.err"]]

dat_out <- data.frame(predictor = rhs,
                      est_beta0 = dat_fit_summary[["Estimate"]][1],
                      conf_int_lb_beta0 = conf_int_lb[1],
                      conf_int_ub_beta0 = conf_int_ub[1],
                      est_beta1 = dat_fit_summary[["Estimate"]][2],
                      conf_int_lb_beta1 = conf_int_lb[2],
                      conf_int_ub_beta1 = conf_int_ub[2])

list_dat_out <- append(list_dat_out, list(dat_out))
```

```{r}
rhs <- "income_val"
lhs <- "Y"
my_formula <- formula(paste(lhs, "~", rhs, sep = ""))

dat_for_analysis <- dat_included %>% select(all_of(c("participant_id", "decision_point", lhs, rhs)))
rows_no_miss <- dat_for_analysis %>% complete.cases(.)
dat_for_analysis_cc <- dat_for_analysis %>% filter(rows_no_miss)

fit <- geeglm(my_formula, 
              data = dat_for_analysis_cc, 
              id = participant_id,
              waves = decision_point,
              family = binomial)
dat_fit_summary <- summary(fit)[["coefficients"]]

conf_int_lb <- dat_fit_summary[["Estimate"]] - qnorm(1 - type_one_error_rate/2) * dat_fit_summary[["Std.err"]]
conf_int_ub <- dat_fit_summary[["Estimate"]] + qnorm(1 - type_one_error_rate/2) * dat_fit_summary[["Std.err"]]

dat_out <- data.frame(predictor = rhs,
                      est_beta0 = dat_fit_summary[["Estimate"]][1],
                      conf_int_lb_beta0 = conf_int_lb[1],
                      conf_int_ub_beta0 = conf_int_ub[1],
                      est_beta1 = dat_fit_summary[["Estimate"]][2],
                      conf_int_lb_beta1 = conf_int_lb[2],
                      conf_int_ub_beta1 = conf_int_ub[2])

list_dat_out <- append(list_dat_out, list(dat_out))
```

```{r}
rhs <- "food_security_mean"
lhs <- "Y"
my_formula <- formula(paste(lhs, "~", rhs, sep = ""))

dat_for_analysis <- dat_included %>% select(all_of(c("participant_id", "decision_point", lhs, rhs)))
rows_no_miss <- dat_for_analysis %>% complete.cases(.)
dat_for_analysis_cc <- dat_for_analysis %>% filter(rows_no_miss)

fit <- geeglm(my_formula, 
              data = dat_for_analysis_cc, 
              id = participant_id,
              waves = decision_point,
              family = binomial)
dat_fit_summary <- summary(fit)[["coefficients"]]

conf_int_lb <- dat_fit_summary[["Estimate"]] - qnorm(1 - type_one_error_rate/2) * dat_fit_summary[["Std.err"]]
conf_int_ub <- dat_fit_summary[["Estimate"]] + qnorm(1 - type_one_error_rate/2) * dat_fit_summary[["Std.err"]]

dat_out <- data.frame(predictor = rhs,
                      est_beta0 = dat_fit_summary[["Estimate"]][1],
                      conf_int_lb_beta0 = conf_int_lb[1],
                      conf_int_ub_beta0 = conf_int_ub[1],
                      est_beta1 = dat_fit_summary[["Estimate"]][2],
                      conf_int_lb_beta1 = conf_int_lb[2],
                      conf_int_ub_beta1 = conf_int_ub[2])

list_dat_out <- append(list_dat_out, list(dat_out))
```

```{r}
rhs <- "SSSladders"
lhs <- "Y"
my_formula <- formula(paste(lhs, "~", rhs, sep = ""))

dat_for_analysis <- dat_included %>% select(all_of(c("participant_id", "decision_point", lhs, rhs)))
rows_no_miss <- dat_for_analysis %>% complete.cases(.)
dat_for_analysis_cc <- dat_for_analysis %>% filter(rows_no_miss)

fit <- geeglm(my_formula, 
              data = dat_for_analysis_cc, 
              id = participant_id,
              waves = decision_point,
              family = binomial)
dat_fit_summary <- summary(fit)[["coefficients"]]

conf_int_lb <- dat_fit_summary[["Estimate"]] - qnorm(1 - type_one_error_rate/2) * dat_fit_summary[["Std.err"]]
conf_int_ub <- dat_fit_summary[["Estimate"]] + qnorm(1 - type_one_error_rate/2) * dat_fit_summary[["Std.err"]]

dat_out <- data.frame(predictor = rhs,
                      est_beta0 = dat_fit_summary[["Estimate"]][1],
                      conf_int_lb_beta0 = conf_int_lb[1],
                      conf_int_ub_beta0 = conf_int_ub[1],
                      est_beta1 = dat_fit_summary[["Estimate"]][2],
                      conf_int_lb_beta1 = conf_int_lb[2],
                      conf_int_ub_beta1 = conf_int_ub[2])

list_dat_out <- append(list_dat_out, list(dat_out))
```

```{r}
rhs <- "pp1_1"
lhs <- "Y"
my_formula <- formula(paste(paste(lhs, "~ 1", sep=""), rhs, sep = "+"))

dat_for_analysis <- dat_included %>% select(all_of(c("participant_id", "decision_point", lhs, rhs)))
rows_no_miss <- dat_for_analysis %>% complete.cases(.)
dat_for_analysis_cc <- dat_for_analysis %>% filter(rows_no_miss)

fit <- geeglm(my_formula, 
              data = dat_for_analysis_cc, 
              id = participant_id,
              waves = decision_point,
              family = binomial)
dat_fit_summary <- summary(fit)[["coefficients"]]

conf_int_lb <- dat_fit_summary[["Estimate"]] - qnorm(1 - type_one_error_rate/2) * dat_fit_summary[["Std.err"]]
conf_int_ub <- dat_fit_summary[["Estimate"]] + qnorm(1 - type_one_error_rate/2) * dat_fit_summary[["Std.err"]]

dat_out <- data.frame(predictor = rhs,
                      est_beta0 = dat_fit_summary[["Estimate"]][1],
                      conf_int_lb_beta0 = conf_int_lb[1],
                      conf_int_ub_beta0 = conf_int_ub[1],
                      est_beta1 = dat_fit_summary[["Estimate"]][2],
                      conf_int_lb_beta1 = conf_int_lb[2],
                      conf_int_ub_beta1 = conf_int_ub[2])

list_dat_out <- append(list_dat_out, list(dat_out))
```

```{r}
rhs <- "FinancialStrain"
lhs <- "Y"
my_formula <- formula(paste(paste(lhs, "~ 1", sep=""), rhs, sep = "+"))

dat_for_analysis <- dat_included %>% select(all_of(c("participant_id", "decision_point", lhs, rhs)))
rows_no_miss <- dat_for_analysis %>% complete.cases(.)
dat_for_analysis_cc <- dat_for_analysis %>% filter(rows_no_miss)

fit <- geeglm(my_formula, 
              data = dat_for_analysis_cc, 
              id = participant_id,
              waves = decision_point,
              family = binomial)
dat_fit_summary <- summary(fit)[["coefficients"]]

conf_int_lb <- dat_fit_summary[["Estimate"]] - qnorm(1 - type_one_error_rate/2) * dat_fit_summary[["Std.err"]]
conf_int_ub <- dat_fit_summary[["Estimate"]] + qnorm(1 - type_one_error_rate/2) * dat_fit_summary[["Std.err"]]

dat_out <- data.frame(predictor = rhs,
                      est_beta0 = dat_fit_summary[["Estimate"]][1],
                      conf_int_lb_beta0 = conf_int_lb[1],
                      conf_int_ub_beta0 = conf_int_ub[1],
                      est_beta1 = dat_fit_summary[["Estimate"]][2],
                      conf_int_lb_beta1 = conf_int_lb[2],
                      conf_int_ub_beta1 = conf_int_ub[2])

list_dat_out <- append(list_dat_out, list(dat_out))
```


```{r}
rhs <- "nd_mean"
lhs <- "Y"
my_formula <- formula(paste(paste(lhs, "~ 1", sep=""), rhs, sep = "+"))

dat_for_analysis <- dat_included %>% select(all_of(c("participant_id", "decision_point", lhs, rhs)))
rows_no_miss <- dat_for_analysis %>% complete.cases(.)
dat_for_analysis_cc <- dat_for_analysis %>% filter(rows_no_miss)

fit <- geeglm(my_formula, 
              data = dat_for_analysis_cc, 
              id = participant_id,
              waves = decision_point,
              family = binomial)
dat_fit_summary <- summary(fit)[["coefficients"]]

conf_int_lb <- dat_fit_summary[["Estimate"]] - qnorm(1 - type_one_error_rate/2) * dat_fit_summary[["Std.err"]]
conf_int_ub <- dat_fit_summary[["Estimate"]] + qnorm(1 - type_one_error_rate/2) * dat_fit_summary[["Std.err"]]

dat_out <- data.frame(predictor = rhs,
                      est_beta0 = dat_fit_summary[["Estimate"]][1],
                      conf_int_lb_beta0 = conf_int_lb[1],
                      conf_int_ub_beta0 = conf_int_ub[1],
                      est_beta1 = dat_fit_summary[["Estimate"]][2],
                      conf_int_lb_beta1 = conf_int_lb[2],
                      conf_int_ub_beta1 = conf_int_ub[2])

list_dat_out <- append(list_dat_out, list(dat_out))
```


```{r}
rhs <- "srq_mean"
lhs <- "Y"
my_formula <- formula(paste(lhs, "~", rhs, sep = ""))

dat_for_analysis <- dat_included %>% select(all_of(c("participant_id", "decision_point", lhs, rhs)))
rows_no_miss <- dat_for_analysis %>% complete.cases(.)
dat_for_analysis_cc <- dat_for_analysis %>% filter(rows_no_miss)

fit <- geeglm(my_formula, 
              data = dat_for_analysis_cc, 
              id = participant_id,
              waves = decision_point,
              family = binomial)
dat_fit_summary <- summary(fit)[["coefficients"]]

conf_int_lb <- dat_fit_summary[["Estimate"]] - qnorm(1 - type_one_error_rate/2) * dat_fit_summary[["Std.err"]]
conf_int_ub <- dat_fit_summary[["Estimate"]] + qnorm(1 - type_one_error_rate/2) * dat_fit_summary[["Std.err"]]

dat_out <- data.frame(predictor = rhs,
                      est_beta0 = dat_fit_summary[["Estimate"]][1],
                      conf_int_lb_beta0 = conf_int_lb[1],
                      conf_int_ub_beta0 = conf_int_ub[1],
                      est_beta1 = dat_fit_summary[["Estimate"]][2],
                      conf_int_lb_beta1 = conf_int_lb[2],
                      conf_int_ub_beta1 = conf_int_ub[2])

list_dat_out <- append(list_dat_out, list(dat_out))
```

```{r}
rhs <- "has_partner"
lhs <- "Y"
my_formula <- formula(paste(lhs, "~", rhs, sep = ""))

dat_for_analysis <- dat_included %>% select(all_of(c("participant_id", "decision_point", lhs, rhs)))
rows_no_miss <- dat_for_analysis %>% complete.cases(.)
dat_for_analysis_cc <- dat_for_analysis %>% filter(rows_no_miss)

fit <- geeglm(my_formula, 
              data = dat_for_analysis_cc, 
              id = participant_id,
              waves = decision_point,
              family = binomial)
dat_fit_summary <- summary(fit)[["coefficients"]]

conf_int_lb <- dat_fit_summary[["Estimate"]] - qnorm(1 - type_one_error_rate/2) * dat_fit_summary[["Std.err"]]
conf_int_ub <- dat_fit_summary[["Estimate"]] + qnorm(1 - type_one_error_rate/2) * dat_fit_summary[["Std.err"]]

dat_out <- data.frame(predictor = rhs,
                      est_beta0 = dat_fit_summary[["Estimate"]][1],
                      conf_int_lb_beta0 = conf_int_lb[1],
                      conf_int_ub_beta0 = conf_int_ub[1],
                      est_beta1 = dat_fit_summary[["Estimate"]][2],
                      conf_int_lb_beta1 = conf_int_lb[2],
                      conf_int_ub_beta1 = conf_int_ub[2])

list_dat_out <- append(list_dat_out, list(dat_out))
```

```{r}
rhs <- "sni_count"
lhs <- "Y"
my_formula <- formula(paste(lhs, "~", rhs, sep = ""))

dat_for_analysis <- dat_included %>% select(all_of(c("participant_id", "decision_point", lhs, rhs)))
rows_no_miss <- dat_for_analysis %>% complete.cases(.)
dat_for_analysis_cc <- dat_for_analysis %>% filter(rows_no_miss)

fit <- geeglm(my_formula, 
              data = dat_for_analysis_cc, 
              id = participant_id,
              waves = decision_point,
              family = binomial)
dat_fit_summary <- summary(fit)[["coefficients"]]

conf_int_lb <- dat_fit_summary[["Estimate"]] - qnorm(1 - type_one_error_rate/2) * dat_fit_summary[["Std.err"]]
conf_int_ub <- dat_fit_summary[["Estimate"]] + qnorm(1 - type_one_error_rate/2) * dat_fit_summary[["Std.err"]]

dat_out <- data.frame(predictor = rhs,
                      est_beta0 = dat_fit_summary[["Estimate"]][1],
                      conf_int_lb_beta0 = conf_int_lb[1],
                      conf_int_ub_beta0 = conf_int_ub[1],
                      est_beta1 = dat_fit_summary[["Estimate"]][2],
                      conf_int_lb_beta1 = conf_int_lb[2],
                      conf_int_ub_beta1 = conf_int_ub[2])

list_dat_out <- append(list_dat_out, list(dat_out))
```


```{r}
rhs <- "sni_people"
lhs <- "Y"
my_formula <- formula(paste(lhs, "~", rhs, sep = ""))

dat_for_analysis <- dat_included %>% select(all_of(c("participant_id", "decision_point", lhs, rhs)))
rows_no_miss <- dat_for_analysis %>% complete.cases(.)
dat_for_analysis_cc <- dat_for_analysis %>% filter(rows_no_miss)

fit <- geeglm(my_formula, 
              data = dat_for_analysis_cc, 
              id = participant_id,
              waves = decision_point,
              family = binomial)
dat_fit_summary <- summary(fit)[["coefficients"]]

conf_int_lb <- dat_fit_summary[["Estimate"]] - qnorm(1 - type_one_error_rate/2) * dat_fit_summary[["Std.err"]]
conf_int_ub <- dat_fit_summary[["Estimate"]] + qnorm(1 - type_one_error_rate/2) * dat_fit_summary[["Std.err"]]

dat_out <- data.frame(predictor = rhs,
                      est_beta0 = dat_fit_summary[["Estimate"]][1],
                      conf_int_lb_beta0 = conf_int_lb[1],
                      conf_int_ub_beta0 = conf_int_ub[1],
                      est_beta1 = dat_fit_summary[["Estimate"]][2],
                      conf_int_lb_beta1 = conf_int_lb[2],
                      conf_int_ub_beta1 = conf_int_ub[2])

list_dat_out <- append(list_dat_out, list(dat_out))
```

```{r}
rhs <- "sni_active"
lhs <- "Y"
my_formula <- formula(paste(lhs, "~", rhs, sep = ""))

dat_for_analysis <- dat_included %>% select(all_of(c("participant_id", "decision_point", lhs, rhs)))
rows_no_miss <- dat_for_analysis %>% complete.cases(.)
dat_for_analysis_cc <- dat_for_analysis %>% filter(rows_no_miss)

fit <- geeglm(my_formula, 
              data = dat_for_analysis_cc, 
              id = participant_id,
              waves = decision_point,
              family = binomial)
dat_fit_summary <- summary(fit)[["coefficients"]]

conf_int_lb <- dat_fit_summary[["Estimate"]] - qnorm(1 - type_one_error_rate/2) * dat_fit_summary[["Std.err"]]
conf_int_ub <- dat_fit_summary[["Estimate"]] + qnorm(1 - type_one_error_rate/2) * dat_fit_summary[["Std.err"]]

dat_out <- data.frame(predictor = rhs,
                      est_beta0 = dat_fit_summary[["Estimate"]][1],
                      conf_int_lb_beta0 = conf_int_lb[1],
                      conf_int_ub_beta0 = conf_int_ub[1],
                      est_beta1 = dat_fit_summary[["Estimate"]][2],
                      conf_int_lb_beta1 = conf_int_lb[2],
                      conf_int_ub_beta1 = conf_int_ub[2])

list_dat_out <- append(list_dat_out, list(dat_out))
```

```{r}
rhs <- "isel_belonging"
lhs <- "Y"
my_formula <- formula(paste(lhs, "~", rhs, sep = ""))

dat_for_analysis <- dat_included %>% select(all_of(c("participant_id", "decision_point", lhs, rhs)))
rows_no_miss <- dat_for_analysis %>% complete.cases(.)
dat_for_analysis_cc <- dat_for_analysis %>% filter(rows_no_miss)

fit <- geeglm(my_formula, 
              data = dat_for_analysis_cc, 
              id = participant_id,
              waves = decision_point,
              family = binomial)
dat_fit_summary <- summary(fit)[["coefficients"]]

conf_int_lb <- dat_fit_summary[["Estimate"]] - qnorm(1 - type_one_error_rate/2) * dat_fit_summary[["Std.err"]]
conf_int_ub <- dat_fit_summary[["Estimate"]] + qnorm(1 - type_one_error_rate/2) * dat_fit_summary[["Std.err"]]

dat_out <- data.frame(predictor = rhs,
                      est_beta0 = dat_fit_summary[["Estimate"]][1],
                      conf_int_lb_beta0 = conf_int_lb[1],
                      conf_int_ub_beta0 = conf_int_ub[1],
                      est_beta1 = dat_fit_summary[["Estimate"]][2],
                      conf_int_lb_beta1 = conf_int_lb[2],
                      conf_int_ub_beta1 = conf_int_ub[2])

list_dat_out <- append(list_dat_out, list(dat_out))
```

```{r}
rhs <- "isel_appraisal"
lhs <- "Y"
my_formula <- formula(paste(lhs, "~", rhs, sep = ""))

dat_for_analysis <- dat_included %>% select(all_of(c("participant_id", "decision_point", lhs, rhs)))
rows_no_miss <- dat_for_analysis %>% complete.cases(.)
dat_for_analysis_cc <- dat_for_analysis %>% filter(rows_no_miss)

fit <- geeglm(my_formula, 
              data = dat_for_analysis_cc, 
              id = participant_id,
              waves = decision_point,
              family = binomial)
dat_fit_summary <- summary(fit)[["coefficients"]]

conf_int_lb <- dat_fit_summary[["Estimate"]] - qnorm(1 - type_one_error_rate/2) * dat_fit_summary[["Std.err"]]
conf_int_ub <- dat_fit_summary[["Estimate"]] + qnorm(1 - type_one_error_rate/2) * dat_fit_summary[["Std.err"]]

dat_out <- data.frame(predictor = rhs,
                      est_beta0 = dat_fit_summary[["Estimate"]][1],
                      conf_int_lb_beta0 = conf_int_lb[1],
                      conf_int_ub_beta0 = conf_int_ub[1],
                      est_beta1 = dat_fit_summary[["Estimate"]][2],
                      conf_int_lb_beta1 = conf_int_lb[2],
                      conf_int_ub_beta1 = conf_int_ub[2])

list_dat_out <- append(list_dat_out, list(dat_out))
```

```{r}
rhs <- "isel_tangible"
lhs <- "Y"
my_formula <- formula(paste(lhs, "~", rhs, sep = ""))

dat_for_analysis <- dat_included %>% select(all_of(c("participant_id", "decision_point", lhs, rhs)))
rows_no_miss <- dat_for_analysis %>% complete.cases(.)
dat_for_analysis_cc <- dat_for_analysis %>% filter(rows_no_miss)

fit <- geeglm(my_formula, 
              data = dat_for_analysis_cc, 
              id = participant_id,
              waves = decision_point,
              family = binomial)
dat_fit_summary <- summary(fit)[["coefficients"]]

conf_int_lb <- dat_fit_summary[["Estimate"]] - qnorm(1 - type_one_error_rate/2) * dat_fit_summary[["Std.err"]]
conf_int_ub <- dat_fit_summary[["Estimate"]] + qnorm(1 - type_one_error_rate/2) * dat_fit_summary[["Std.err"]]

dat_out <- data.frame(predictor = rhs,
                      est_beta0 = dat_fit_summary[["Estimate"]][1],
                      conf_int_lb_beta0 = conf_int_lb[1],
                      conf_int_ub_beta0 = conf_int_ub[1],
                      est_beta1 = dat_fit_summary[["Estimate"]][2],
                      conf_int_lb_beta1 = conf_int_lb[2],
                      conf_int_ub_beta1 = conf_int_ub[2])

list_dat_out <- append(list_dat_out, list(dat_out))
```

```{r}
dat_all_out <- bind_rows(list_dat_out)
dat_all_out <- dat_all_out %>% mutate(screened_out = if_else((conf_int_lb_beta1 <=0) & (conf_int_ub_beta1 >=0), 1, 0))
dat_all_out %>% mutate(across(-any_of("predictor"), ~round(.x, 3)))

dat_all_out <- dat_all_out %>% mutate(across(-any_of("predictor"), ~round(.x, 3))) 
write.csv(dat_all_out, file.path(path_code, "analysis-multiple-imputation", "diagnostics", "stratum01_linear.csv"))
```

# Enter predictors as a quadratic main effect


```{r}
rhs <- "hour_coinflip_local"
lhs <- "Y"
my_formula <- formula(paste(lhs, "~", rhs, paste(" + I(", rhs , " * ", rhs, ")", sep = ""), sep = ""))

dat_for_analysis <- dat_included %>% select(all_of(c("participant_id", "decision_point", lhs, rhs)))
rows_no_miss <- dat_for_analysis %>% complete.cases(.)
dat_for_analysis_cc <- dat_for_analysis %>% filter(rows_no_miss)

fit <- geeglm(my_formula, 
              data = dat_for_analysis_cc, 
              id = participant_id,
              waves = decision_point,
              family = binomial)
dat_fit_summary <- summary(fit)[["coefficients"]]

conf_int_lb <- dat_fit_summary[["Estimate"]] - qnorm(1 - type_one_error_rate/2) * dat_fit_summary[["Std.err"]]
conf_int_ub <- dat_fit_summary[["Estimate"]] + qnorm(1 - type_one_error_rate/2) * dat_fit_summary[["Std.err"]]

dat_out <- data.frame(predictor = rhs,
                      est_beta0 = dat_fit_summary[["Estimate"]][1],
                      conf_int_lb_beta0 = conf_int_lb[1],
                      conf_int_ub_beta0 = conf_int_ub[1],
                      est_beta1 = dat_fit_summary[["Estimate"]][2],
                      conf_int_lb_beta1 = conf_int_lb[2],
                      conf_int_ub_beta1 = conf_int_ub[2],
                      est_beta2 = dat_fit_summary[["Estimate"]][3],
                      conf_int_lb_beta2 = conf_int_lb[3],
                      conf_int_ub_beta2 = conf_int_ub[3])

list_dat_out_quadratic <- append(list_dat_out_quadratic, list(dat_out))
```

```{r}
rhs <- "age"
lhs <- "Y"
my_formula <- formula(paste(lhs, "~", rhs, paste(" + I(", rhs , " * ", rhs, ")", sep = ""), sep = ""))

dat_for_analysis <- dat_included %>% select(all_of(c("participant_id", "decision_point", lhs, rhs)))
rows_no_miss <- dat_for_analysis %>% complete.cases(.)
dat_for_analysis_cc <- dat_for_analysis %>% filter(rows_no_miss)

fit <- geeglm(my_formula, 
              data = dat_for_analysis_cc, 
              id = participant_id,
              waves = decision_point,
              family = binomial)
dat_fit_summary <- summary(fit)[["coefficients"]]

conf_int_lb <- dat_fit_summary[["Estimate"]] - qnorm(1 - type_one_error_rate/2) * dat_fit_summary[["Std.err"]]
conf_int_ub <- dat_fit_summary[["Estimate"]] + qnorm(1 - type_one_error_rate/2) * dat_fit_summary[["Std.err"]]

dat_out <- data.frame(predictor = rhs,
                      est_beta0 = dat_fit_summary[["Estimate"]][1],
                      conf_int_lb_beta0 = conf_int_lb[1],
                      conf_int_ub_beta0 = conf_int_ub[1],
                      est_beta1 = dat_fit_summary[["Estimate"]][2],
                      conf_int_lb_beta1 = conf_int_lb[2],
                      conf_int_ub_beta1 = conf_int_ub[2],
                      est_beta2 = dat_fit_summary[["Estimate"]][3],
                      conf_int_lb_beta2 = conf_int_lb[3],
                      conf_int_ub_beta2 = conf_int_ub[3])

list_dat_out_quadratic <- append(list_dat_out_quadratic, list(dat_out))
```

```{r}
rhs <- "income_val"
lhs <- "Y"
my_formula <- formula(paste(lhs, "~", rhs, paste(" + I(", rhs , " * ", rhs, ")", sep = ""), sep = ""))

dat_for_analysis <- dat_included %>% select(all_of(c("participant_id", "decision_point", lhs, rhs)))
rows_no_miss <- dat_for_analysis %>% complete.cases(.)
dat_for_analysis_cc <- dat_for_analysis %>% filter(rows_no_miss)

fit <- geeglm(my_formula, 
              data = dat_for_analysis_cc, 
              id = participant_id,
              waves = decision_point,
              family = binomial)
dat_fit_summary <- summary(fit)[["coefficients"]]

conf_int_lb <- dat_fit_summary[["Estimate"]] - qnorm(1 - type_one_error_rate/2) * dat_fit_summary[["Std.err"]]
conf_int_ub <- dat_fit_summary[["Estimate"]] + qnorm(1 - type_one_error_rate/2) * dat_fit_summary[["Std.err"]]

dat_out <- data.frame(predictor = rhs,
                      est_beta0 = dat_fit_summary[["Estimate"]][1],
                      conf_int_lb_beta0 = conf_int_lb[1],
                      conf_int_ub_beta0 = conf_int_ub[1],
                      est_beta1 = dat_fit_summary[["Estimate"]][2],
                      conf_int_lb_beta1 = conf_int_lb[2],
                      conf_int_ub_beta1 = conf_int_ub[2],
                      est_beta2 = dat_fit_summary[["Estimate"]][3],
                      conf_int_lb_beta2 = conf_int_lb[3],
                      conf_int_ub_beta2 = conf_int_ub[3])

list_dat_out_quadratic <- append(list_dat_out_quadratic, list(dat_out))
```

```{r}
rhs <- "food_security_mean"
lhs <- "Y"
my_formula <- formula(paste(lhs, "~", rhs, paste(" + I(", rhs , " * ", rhs, ")", sep = ""), sep = ""))

dat_for_analysis <- dat_included %>% select(all_of(c("participant_id", "decision_point", lhs, rhs)))
rows_no_miss <- dat_for_analysis %>% complete.cases(.)
dat_for_analysis_cc <- dat_for_analysis %>% filter(rows_no_miss)

fit <- geeglm(my_formula, 
              data = dat_for_analysis_cc, 
              id = participant_id,
              waves = decision_point,
              family = binomial)
dat_fit_summary <- summary(fit)[["coefficients"]]

conf_int_lb <- dat_fit_summary[["Estimate"]] - qnorm(1 - type_one_error_rate/2) * dat_fit_summary[["Std.err"]]
conf_int_ub <- dat_fit_summary[["Estimate"]] + qnorm(1 - type_one_error_rate/2) * dat_fit_summary[["Std.err"]]

dat_out <- data.frame(predictor = rhs,
                      est_beta0 = dat_fit_summary[["Estimate"]][1],
                      conf_int_lb_beta0 = conf_int_lb[1],
                      conf_int_ub_beta0 = conf_int_ub[1],
                      est_beta1 = dat_fit_summary[["Estimate"]][2],
                      conf_int_lb_beta1 = conf_int_lb[2],
                      conf_int_ub_beta1 = conf_int_ub[2],
                      est_beta2 = dat_fit_summary[["Estimate"]][3],
                      conf_int_lb_beta2 = conf_int_lb[3],
                      conf_int_ub_beta2 = conf_int_ub[3])

list_dat_out_quadratic <- append(list_dat_out_quadratic, list(dat_out))
```

```{r}
rhs <- "SSSladders"
lhs <- "Y"
my_formula <- formula(paste(lhs, "~", rhs, paste(" + I(", rhs , " * ", rhs, ")", sep = ""), sep = ""))

dat_for_analysis <- dat_included %>% select(all_of(c("participant_id", "decision_point", lhs, rhs)))
rows_no_miss <- dat_for_analysis %>% complete.cases(.)
dat_for_analysis_cc <- dat_for_analysis %>% filter(rows_no_miss)

fit <- geeglm(my_formula, 
              data = dat_for_analysis_cc, 
              id = participant_id,
              waves = decision_point,
              family = binomial)
dat_fit_summary <- summary(fit)[["coefficients"]]

conf_int_lb <- dat_fit_summary[["Estimate"]] - qnorm(1 - type_one_error_rate/2) * dat_fit_summary[["Std.err"]]
conf_int_ub <- dat_fit_summary[["Estimate"]] + qnorm(1 - type_one_error_rate/2) * dat_fit_summary[["Std.err"]]

dat_out <- data.frame(predictor = rhs,
                      est_beta0 = dat_fit_summary[["Estimate"]][1],
                      conf_int_lb_beta0 = conf_int_lb[1],
                      conf_int_ub_beta0 = conf_int_ub[1],
                      est_beta1 = dat_fit_summary[["Estimate"]][2],
                      conf_int_lb_beta1 = conf_int_lb[2],
                      conf_int_ub_beta1 = conf_int_ub[2],
                      est_beta2 = dat_fit_summary[["Estimate"]][3],
                      conf_int_lb_beta2 = conf_int_lb[3],
                      conf_int_ub_beta2 = conf_int_ub[3])

list_dat_out_quadratic <- append(list_dat_out_quadratic, list(dat_out))
```

```{r}
rhs <- "pp1_1"
lhs <- "Y"
my_formula <- formula(paste(lhs, "~", rhs, paste(" + I(", rhs , " * ", rhs, ")", sep = ""), sep = ""))

dat_for_analysis <- dat_included %>% select(all_of(c("participant_id", "decision_point", lhs, rhs)))
rows_no_miss <- dat_for_analysis %>% complete.cases(.)
dat_for_analysis_cc <- dat_for_analysis %>% filter(rows_no_miss)

fit <- geeglm(my_formula, 
              data = dat_for_analysis_cc, 
              id = participant_id,
              waves = decision_point,
              family = binomial)
dat_fit_summary <- summary(fit)[["coefficients"]]

conf_int_lb <- dat_fit_summary[["Estimate"]] - qnorm(1 - type_one_error_rate/2) * dat_fit_summary[["Std.err"]]
conf_int_ub <- dat_fit_summary[["Estimate"]] + qnorm(1 - type_one_error_rate/2) * dat_fit_summary[["Std.err"]]

dat_out <- data.frame(predictor = rhs,
                      est_beta0 = dat_fit_summary[["Estimate"]][1],
                      conf_int_lb_beta0 = conf_int_lb[1],
                      conf_int_ub_beta0 = conf_int_ub[1],
                      est_beta1 = dat_fit_summary[["Estimate"]][2],
                      conf_int_lb_beta1 = conf_int_lb[2],
                      conf_int_ub_beta1 = conf_int_ub[2],
                      est_beta2 = dat_fit_summary[["Estimate"]][3],
                      conf_int_lb_beta2 = conf_int_lb[3],
                      conf_int_ub_beta2 = conf_int_ub[3])

list_dat_out_quadratic <- append(list_dat_out_quadratic, list(dat_out))
```

```{r}
rhs <- "FinancialStrain"
lhs <- "Y"
my_formula <- formula(paste(lhs, "~", rhs, paste(" + I(", rhs , " * ", rhs, ")", sep = ""), sep = ""))

dat_for_analysis <- dat_included %>% select(all_of(c("participant_id", "decision_point", lhs, rhs)))
rows_no_miss <- dat_for_analysis %>% complete.cases(.)
dat_for_analysis_cc <- dat_for_analysis %>% filter(rows_no_miss)

fit <- geeglm(my_formula, 
              data = dat_for_analysis_cc, 
              id = participant_id,
              waves = decision_point,
              family = binomial)
dat_fit_summary <- summary(fit)[["coefficients"]]

conf_int_lb <- dat_fit_summary[["Estimate"]] - qnorm(1 - type_one_error_rate/2) * dat_fit_summary[["Std.err"]]
conf_int_ub <- dat_fit_summary[["Estimate"]] + qnorm(1 - type_one_error_rate/2) * dat_fit_summary[["Std.err"]]

dat_out <- data.frame(predictor = rhs,
                      est_beta0 = dat_fit_summary[["Estimate"]][1],
                      conf_int_lb_beta0 = conf_int_lb[1],
                      conf_int_ub_beta0 = conf_int_ub[1],
                      est_beta1 = dat_fit_summary[["Estimate"]][2],
                      conf_int_lb_beta1 = conf_int_lb[2],
                      conf_int_ub_beta1 = conf_int_ub[2],
                      est_beta2 = dat_fit_summary[["Estimate"]][3],
                      conf_int_lb_beta2 = conf_int_lb[3],
                      conf_int_ub_beta2 = conf_int_ub[3])

list_dat_out_quadratic <- append(list_dat_out_quadratic, list(dat_out))
```

```{r}
rhs <- "nd_mean"
lhs <- "Y"
my_formula <- formula(paste(lhs, "~", rhs, paste(" + I(", rhs , " * ", rhs, ")", sep = ""), sep = ""))

dat_for_analysis <- dat_included %>% select(all_of(c("participant_id", "decision_point", lhs, rhs)))
rows_no_miss <- dat_for_analysis %>% complete.cases(.)
dat_for_analysis_cc <- dat_for_analysis %>% filter(rows_no_miss)

fit <- geeglm(my_formula, 
              data = dat_for_analysis_cc, 
              id = participant_id,
              waves = decision_point,
              family = binomial)
dat_fit_summary <- summary(fit)[["coefficients"]]

conf_int_lb <- dat_fit_summary[["Estimate"]] - qnorm(1 - type_one_error_rate/2) * dat_fit_summary[["Std.err"]]
conf_int_ub <- dat_fit_summary[["Estimate"]] + qnorm(1 - type_one_error_rate/2) * dat_fit_summary[["Std.err"]]

dat_out <- data.frame(predictor = rhs,
                      est_beta0 = dat_fit_summary[["Estimate"]][1],
                      conf_int_lb_beta0 = conf_int_lb[1],
                      conf_int_ub_beta0 = conf_int_ub[1],
                      est_beta1 = dat_fit_summary[["Estimate"]][2],
                      conf_int_lb_beta1 = conf_int_lb[2],
                      conf_int_ub_beta1 = conf_int_ub[2],
                      est_beta2 = dat_fit_summary[["Estimate"]][3],
                      conf_int_lb_beta2 = conf_int_lb[3],
                      conf_int_ub_beta2 = conf_int_ub[3])

list_dat_out_quadratic <- append(list_dat_out_quadratic, list(dat_out))
```

```{r}
rhs <- "srq_mean"
lhs <- "Y"
my_formula <- formula(paste(lhs, "~", rhs, paste(" + I(", rhs , " * ", rhs, ")", sep = ""), sep = ""))

dat_for_analysis <- dat_included %>% select(all_of(c("participant_id", "decision_point", lhs, rhs)))
rows_no_miss <- dat_for_analysis %>% complete.cases(.)
dat_for_analysis_cc <- dat_for_analysis %>% filter(rows_no_miss)

fit <- geeglm(my_formula, 
              data = dat_for_analysis_cc, 
              id = participant_id,
              waves = decision_point,
              family = binomial)
dat_fit_summary <- summary(fit)[["coefficients"]]

conf_int_lb <- dat_fit_summary[["Estimate"]] - qnorm(1 - type_one_error_rate/2) * dat_fit_summary[["Std.err"]]
conf_int_ub <- dat_fit_summary[["Estimate"]] + qnorm(1 - type_one_error_rate/2) * dat_fit_summary[["Std.err"]]

dat_out <- data.frame(predictor = rhs,
                      est_beta0 = dat_fit_summary[["Estimate"]][1],
                      conf_int_lb_beta0 = conf_int_lb[1],
                      conf_int_ub_beta0 = conf_int_ub[1],
                      est_beta1 = dat_fit_summary[["Estimate"]][2],
                      conf_int_lb_beta1 = conf_int_lb[2],
                      conf_int_ub_beta1 = conf_int_ub[2],
                      est_beta2 = dat_fit_summary[["Estimate"]][3],
                      conf_int_lb_beta2 = conf_int_lb[3],
                      conf_int_ub_beta2 = conf_int_ub[3])

list_dat_out_quadratic <- append(list_dat_out_quadratic, list(dat_out))
```

```{r}
rhs <- "sni_count"
lhs <- "Y"
my_formula <- formula(paste(lhs, "~", rhs, paste(" + I(", rhs , " * ", rhs, ")", sep = ""), sep = ""))

dat_for_analysis <- dat_included %>% select(all_of(c("participant_id", "decision_point", lhs, rhs)))
rows_no_miss <- dat_for_analysis %>% complete.cases(.)
dat_for_analysis_cc <- dat_for_analysis %>% filter(rows_no_miss)

fit <- geeglm(my_formula, 
              data = dat_for_analysis_cc, 
              id = participant_id,
              waves = decision_point,
              family = binomial)
dat_fit_summary <- summary(fit)[["coefficients"]]

conf_int_lb <- dat_fit_summary[["Estimate"]] - qnorm(1 - type_one_error_rate/2) * dat_fit_summary[["Std.err"]]
conf_int_ub <- dat_fit_summary[["Estimate"]] + qnorm(1 - type_one_error_rate/2) * dat_fit_summary[["Std.err"]]

dat_out <- data.frame(predictor = rhs,
                      est_beta0 = dat_fit_summary[["Estimate"]][1],
                      conf_int_lb_beta0 = conf_int_lb[1],
                      conf_int_ub_beta0 = conf_int_ub[1],
                      est_beta1 = dat_fit_summary[["Estimate"]][2],
                      conf_int_lb_beta1 = conf_int_lb[2],
                      conf_int_ub_beta1 = conf_int_ub[2],
                      est_beta2 = dat_fit_summary[["Estimate"]][3],
                      conf_int_lb_beta2 = conf_int_lb[3],
                      conf_int_ub_beta2 = conf_int_ub[3])

list_dat_out_quadratic <- append(list_dat_out_quadratic, list(dat_out))
```

```{r}
rhs <- "sni_people"
lhs <- "Y"
my_formula <- formula(paste(lhs, "~", rhs, paste(" + I(", rhs , " * ", rhs, ")", sep = ""), sep = ""))

dat_for_analysis <- dat_included %>% select(all_of(c("participant_id", "decision_point", lhs, rhs)))
rows_no_miss <- dat_for_analysis %>% complete.cases(.)
dat_for_analysis_cc <- dat_for_analysis %>% filter(rows_no_miss)

fit <- geeglm(my_formula, 
              data = dat_for_analysis_cc, 
              id = participant_id,
              waves = decision_point,
              family = binomial)
dat_fit_summary <- summary(fit)[["coefficients"]]

conf_int_lb <- dat_fit_summary[["Estimate"]] - qnorm(1 - type_one_error_rate/2) * dat_fit_summary[["Std.err"]]
conf_int_ub <- dat_fit_summary[["Estimate"]] + qnorm(1 - type_one_error_rate/2) * dat_fit_summary[["Std.err"]]

dat_out <- data.frame(predictor = rhs,
                      est_beta0 = dat_fit_summary[["Estimate"]][1],
                      conf_int_lb_beta0 = conf_int_lb[1],
                      conf_int_ub_beta0 = conf_int_ub[1],
                      est_beta1 = dat_fit_summary[["Estimate"]][2],
                      conf_int_lb_beta1 = conf_int_lb[2],
                      conf_int_ub_beta1 = conf_int_ub[2],
                      est_beta2 = dat_fit_summary[["Estimate"]][3],
                      conf_int_lb_beta2 = conf_int_lb[3],
                      conf_int_ub_beta2 = conf_int_ub[3])

list_dat_out_quadratic <- append(list_dat_out_quadratic, list(dat_out))
```

```{r}
rhs <- "sni_active"
lhs <- "Y"
my_formula <- formula(paste(lhs, "~", rhs, paste(" + I(", rhs , " * ", rhs, ")", sep = ""), sep = ""))

dat_for_analysis <- dat_included %>% select(all_of(c("participant_id", "decision_point", lhs, rhs)))
rows_no_miss <- dat_for_analysis %>% complete.cases(.)
dat_for_analysis_cc <- dat_for_analysis %>% filter(rows_no_miss)

fit <- geeglm(my_formula, 
              data = dat_for_analysis_cc, 
              id = participant_id,
              waves = decision_point,
              family = binomial)
dat_fit_summary <- summary(fit)[["coefficients"]]

conf_int_lb <- dat_fit_summary[["Estimate"]] - qnorm(1 - type_one_error_rate/2) * dat_fit_summary[["Std.err"]]
conf_int_ub <- dat_fit_summary[["Estimate"]] + qnorm(1 - type_one_error_rate/2) * dat_fit_summary[["Std.err"]]

dat_out <- data.frame(predictor = rhs,
                      est_beta0 = dat_fit_summary[["Estimate"]][1],
                      conf_int_lb_beta0 = conf_int_lb[1],
                      conf_int_ub_beta0 = conf_int_ub[1],
                      est_beta1 = dat_fit_summary[["Estimate"]][2],
                      conf_int_lb_beta1 = conf_int_lb[2],
                      conf_int_ub_beta1 = conf_int_ub[2],
                      est_beta2 = dat_fit_summary[["Estimate"]][3],
                      conf_int_lb_beta2 = conf_int_lb[3],
                      conf_int_ub_beta2 = conf_int_ub[3])

list_dat_out_quadratic <- append(list_dat_out_quadratic, list(dat_out))
```

```{r}
rhs <- "isel_belonging"
lhs <- "Y"
my_formula <- formula(paste(lhs, "~", rhs, paste(" + I(", rhs , " * ", rhs, ")", sep = ""), sep = ""))

dat_for_analysis <- dat_included %>% select(all_of(c("participant_id", "decision_point", lhs, rhs)))
rows_no_miss <- dat_for_analysis %>% complete.cases(.)
dat_for_analysis_cc <- dat_for_analysis %>% filter(rows_no_miss)

fit <- geeglm(my_formula, 
              data = dat_for_analysis_cc, 
              id = participant_id,
              waves = decision_point,
              family = binomial)
dat_fit_summary <- summary(fit)[["coefficients"]]

conf_int_lb <- dat_fit_summary[["Estimate"]] - qnorm(1 - type_one_error_rate/2) * dat_fit_summary[["Std.err"]]
conf_int_ub <- dat_fit_summary[["Estimate"]] + qnorm(1 - type_one_error_rate/2) * dat_fit_summary[["Std.err"]]

dat_out <- data.frame(predictor = rhs,
                      est_beta0 = dat_fit_summary[["Estimate"]][1],
                      conf_int_lb_beta0 = conf_int_lb[1],
                      conf_int_ub_beta0 = conf_int_ub[1],
                      est_beta1 = dat_fit_summary[["Estimate"]][2],
                      conf_int_lb_beta1 = conf_int_lb[2],
                      conf_int_ub_beta1 = conf_int_ub[2],
                      est_beta2 = dat_fit_summary[["Estimate"]][3],
                      conf_int_lb_beta2 = conf_int_lb[3],
                      conf_int_ub_beta2 = conf_int_ub[3])

list_dat_out_quadratic <- append(list_dat_out_quadratic, list(dat_out))
```

```{r}
rhs <- "isel_appraisal"
lhs <- "Y"
my_formula <- formula(paste(lhs, "~", rhs, paste(" + I(", rhs , " * ", rhs, ")", sep = ""), sep = ""))

dat_for_analysis <- dat_included %>% select(all_of(c("participant_id", "decision_point", lhs, rhs)))
rows_no_miss <- dat_for_analysis %>% complete.cases(.)
dat_for_analysis_cc <- dat_for_analysis %>% filter(rows_no_miss)

fit <- geeglm(my_formula, 
              data = dat_for_analysis_cc, 
              id = participant_id,
              waves = decision_point,
              family = binomial)
dat_fit_summary <- summary(fit)[["coefficients"]]

conf_int_lb <- dat_fit_summary[["Estimate"]] - qnorm(1 - type_one_error_rate/2) * dat_fit_summary[["Std.err"]]
conf_int_ub <- dat_fit_summary[["Estimate"]] + qnorm(1 - type_one_error_rate/2) * dat_fit_summary[["Std.err"]]

dat_out <- data.frame(predictor = rhs,
                      est_beta0 = dat_fit_summary[["Estimate"]][1],
                      conf_int_lb_beta0 = conf_int_lb[1],
                      conf_int_ub_beta0 = conf_int_ub[1],
                      est_beta1 = dat_fit_summary[["Estimate"]][2],
                      conf_int_lb_beta1 = conf_int_lb[2],
                      conf_int_ub_beta1 = conf_int_ub[2],
                      est_beta2 = dat_fit_summary[["Estimate"]][3],
                      conf_int_lb_beta2 = conf_int_lb[3],
                      conf_int_ub_beta2 = conf_int_ub[3])

list_dat_out_quadratic <- append(list_dat_out_quadratic, list(dat_out))
```

```{r}
rhs <- "isel_tangible"
lhs <- "Y"
my_formula <- formula(paste(lhs, "~", rhs, paste(" + I(", rhs , " * ", rhs, ")", sep = ""), sep = ""))

dat_for_analysis <- dat_included %>% select(all_of(c("participant_id", "decision_point", lhs, rhs)))
rows_no_miss <- dat_for_analysis %>% complete.cases(.)
dat_for_analysis_cc <- dat_for_analysis %>% filter(rows_no_miss)

fit <- geeglm(my_formula, 
              data = dat_for_analysis_cc, 
              id = participant_id,
              waves = decision_point,
              family = binomial)
dat_fit_summary <- summary(fit)[["coefficients"]]

conf_int_lb <- dat_fit_summary[["Estimate"]] - qnorm(1 - type_one_error_rate/2) * dat_fit_summary[["Std.err"]]
conf_int_ub <- dat_fit_summary[["Estimate"]] + qnorm(1 - type_one_error_rate/2) * dat_fit_summary[["Std.err"]]

dat_out <- data.frame(predictor = rhs,
                      est_beta0 = dat_fit_summary[["Estimate"]][1],
                      conf_int_lb_beta0 = conf_int_lb[1],
                      conf_int_ub_beta0 = conf_int_ub[1],
                      est_beta1 = dat_fit_summary[["Estimate"]][2],
                      conf_int_lb_beta1 = conf_int_lb[2],
                      conf_int_ub_beta1 = conf_int_ub[2],
                      est_beta2 = dat_fit_summary[["Estimate"]][3],
                      conf_int_lb_beta2 = conf_int_lb[3],
                      conf_int_ub_beta2 = conf_int_ub[3])

list_dat_out_quadratic <- append(list_dat_out_quadratic, list(dat_out))
```

```{r}
dat_all_out_quadratic <- bind_rows(list_dat_out_quadratic)
dat_all_out_quadratic <- dat_all_out_quadratic %>% mutate(screened_out = if_else((conf_int_lb_beta2 <=0) & (conf_int_ub_beta2 >=0), 1, 0))
dat_all_out_quadratic %>% mutate(across(-any_of("predictor"), ~round(.x, 3)))

dat_all_out_quadratic <- dat_all_out_quadratic %>% mutate(across(-any_of("predictor"), ~round(.x, 3))) 
write.csv(dat_all_out_quadratic, file.path(path_code, "analysis-multiple-imputation", "diagnostics", "stratum01_quadratic.csv"))
```

